# Generated by Django 3.2.3 on 2021-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=50)),
                ('std_contact', models.IntegerField(unique=True)),
                ('std_email', models.CharField(max_length=50, unique=True)),
                ('std_password', models.CharField(max_length=20)),
                ('std_otp', models.IntegerField(default=0)),
                ('std_otp_sts', models.CharField(default='Pending', max_length=10)),
                ('std_reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
